/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloFromLib: typeof import('./../../../libs/libcomponents/src/components/HelloFromLib.vue')['default']
    HelloFromMain: typeof import('./components/HelloFromMain.vue')['default']
    UnimportedHelloFromLib: typeof import('./../../../libs/libcomponents/src/components/UnimportedHelloFromLib.vue')['default']
    UnimportedHelloFromMain: typeof import('./components/UnimportedHelloFromMain.vue')['default']
  }
}
